#!/usr/bin/env python3
"""Generate shareable OCR inputs from synthetic text and repository fonts only."""
import argparse
import hashlib
import json
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont, __version__ as pillow_version

ROOT = Path(__file__).resolve().parents[1]
ENGLISH = [
    "Invoice OCR 2026 total amount 12345",
    "Please verify customer number 80421",
    "Document conversion preserves editable text",
    "Local processing keeps source files private",
    "Table fields include date quantity and price",
    "Scan quality improves with straight text lines",
    "The final amount is 9876 and invoice is 2026",
    "Review each converted paragraph before sharing",
]
CHINESE = [
    "会议记录：文档转换测试。", "发票金额12345元，请核对。",
    "客户名称与编号需要保留。", "扫描图片应保持文字完整。",
    "本地识别保护原始文件。", "测试中文标点、数字和日期。",
    "转换结果仍然可以编辑。", "请复核各行内容后再分享。",
]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=ROOT / "qa-samples/generated/cloud-handoff")
    args = parser.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)
    fonts = ROOT / "task-service/src/main/resources/fonts"
    latin = ImageFont.truetype(str(fonts / "LiberationSans-Regular.ttf"), 32)
    latin_large = ImageFont.truetype(str(fonts / "LiberationSans-Regular.ttf"), 42)
    chinese = ImageFont.truetype(str(fonts / "DroidSansFallback.ttf"), 42)
    cases = []

    for language, lines in [("english", ENGLISH), ("chinese", CHINESE)]:
        original = Image.new("RGB", (1400, 1000), "white")
        draw = ImageDraw.Draw(original)
        for index, line in enumerate(lines):
            x, baseline = 150.0, 125 + 100 * index
            if language == "english":
                draw.text((x, baseline), line, font=latin, fill="black", anchor="ls")
            else:
                for char in line:
                    font = latin_large if char.isascii() else chinese
                    draw.text((x, baseline), char, font=font, fill="black", anchor="ls")
                    x += font.getlength(char)
        for degrees in [0, -6, 6]:
            # Image y grows downward: negative Pillow rotation produces positive source skew.
            image = original.rotate(-degrees, resample=Image.Resampling.BICUBIC, expand=False, fillcolor="white")
            filename = f"{language}-tilt-{degrees:+d}.png"
            target = args.out / filename
            image.save(target, dpi=(300, 300))
            cases.append({"file": filename, "language": language, "sourceSkewDegrees": degrees,
                          "expectedLines": lines, "size": list(image.size),
                          "sha256": hashlib.sha256(target.read_bytes()).hexdigest()})
            image.close()
        original.close()
    manifest = {"provenance": "Synthetic text generated by repository code; no user documents or real invoices",
                "pillowVersion": pillow_version,
                "fontLicenses": ["task-service/src/main/resources/fonts/LiberationSans-LICENSE.txt",
                                 "task-service/src/main/resources/fonts/DroidSansFallback-NOTICE.txt"],
                "cases": cases}
    (args.out / "expected.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Generated {len(cases)} synthetic OCR inputs and expected.json in {args.out}")


if __name__ == "__main__":
    main()
