package com.fuyue.formatconverter.model;

public enum WarningCode {
    MVP_FIRST_PAGE_ONLY,
    OCR_REQUIRED,
    OCR_APPLIED,
    OCR_LOW_CONFIDENCE,
    UNSUPPORTED_OFD_ELEMENT,
    FONT_SUBSTITUTED,
    TABLE_RECOGNITION_UNRELIABLE,
    AMBIGUOUS_MERGE,
    TEXT_CROSSES_CELL_BORDER,
    IMAGE_EXTRACTION_FAILED,
    SIGNATURE_APPEARANCE_FAILED,
    UNSUPPORTED_TEXT_TRANSFORM,
    TEXT_ENCODING_GUESSED,
    CSV_DELIMITER_DETECTED,
    FORMULA_RESULT_EXPORTED,
    MULTI_SHEET_ARCHIVE,
    IMAGE_DPI_DEFAULTED,
    EXIF_ORIENTATION_APPLIED,
    PARTIAL_BATCH_OUTPUT,
    FIDELITY_IMAGE_LAYER,
    OFFICE_COMPATIBILITY_LAYOUT
}
