package com.fuyue.formatconverter.model;

public enum WarningCode {
    MVP_FIRST_PAGE_ONLY,
    OCR_REQUIRED,
    UNSUPPORTED_OFD_ELEMENT,
    FONT_SUBSTITUTED,
    TABLE_RECOGNITION_UNRELIABLE,
    AMBIGUOUS_MERGE,
    TEXT_CROSSES_CELL_BORDER,
    IMAGE_EXTRACTION_FAILED,
    SIGNATURE_APPEARANCE_FAILED,
    UNSUPPORTED_TEXT_TRANSFORM,
    TEXT_ENCODING_GUESSED,
    FIDELITY_IMAGE_LAYER,
    OFFICE_COMPATIBILITY_LAYOUT
}
